const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "92478351899" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "92478351899";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_13_54_10_19_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTMsXG4gICAgICAgIDExNSxcbiAgICAgICAgNDQsXG4gICAgICAgIDcxLFxuICAgICAgICA0NixcbiAgICAgICAgNzksXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNyxcbiAgICAgICAgNTEsXG4gICAgICAgIDE5NSxcbiAgICAgICAgOTUsXG4gICAgICAgIDQsXG4gICAgICAgIDYzLFxuICAgICAgICA2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDk4LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMzAsXG4gICAgICAgIDExNixcbiAgICAgICAgMTc0LFxuICAgICAgICA2NixcbiAgICAgICAgMjEyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDE5LFxuICAgICAgICA0LFxuICAgICAgICA2MCxcbiAgICAgICAgNSxcbiAgICAgICAgMTA3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxMTYsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE1NyxcbiAgICAgICAgOTEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgOTcsXG4gICAgICAgIDkyLFxuICAgICAgICAyMzksXG4gICAgICAgIDksXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNjksXG4gICAgICAgIDc5LFxuICAgICAgICAxNDUsXG4gICAgICAgIDc0LFxuICAgICAgICAxNDksXG4gICAgICAgIDMzLFxuICAgICAgICAxMDAsXG4gICAgICAgIDcyLFxuICAgICAgICAyNCxcbiAgICAgICAgNzgsXG4gICAgICAgIDgxLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTQyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTkyLFxuICAgICAgICAyNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDI5LFxuICAgICAgICAxNjEsXG4gICAgICAgIDM2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDU2LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTc3LFxuICAgICAgICA5NixcbiAgICAgICAgMjM3LFxuICAgICAgICAyNDEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTEzLFxuICAgICAgICAyNDUsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjQsXG4gICAgICAgIDc4LFxuICAgICAgICAyMzUsXG4gICAgICAgIDI4LFxuICAgICAgICAxMDUsXG4gICAgICAgIDM4LFxuICAgICAgICA3OCxcbiAgICAgICAgMTAsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNjUsXG4gICAgICAgIDcxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDkzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTYxLFxuICAgICAgICAxMDMsXG4gICAgICAgIDYsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMSxcbiAgICAgICAgOTcsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDI0MSxcbiAgICAgICAgNTgsXG4gICAgICAgIDg0LFxuICAgICAgICAyMzIsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMjEsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjA0LFxuICAgICAgICAyNDgsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTU0LFxuICAgICAgICAxODIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTU5LFxuICAgICAgICA4OVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDQ3LFxuICAgICAgICAyNSxcbiAgICAgICAgMzYsXG4gICAgICAgIDU2LFxuICAgICAgICA0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjM5LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxODQsXG4gICAgICAgIDk1LFxuICAgICAgICAyMzksXG4gICAgICAgIDE4MSxcbiAgICAgICAgODksXG4gICAgICAgIDEyOCxcbiAgICAgICAgNzEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTg1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDY3LFxuICAgICAgICAxNjMsXG4gICAgICAgIDM3LFxuICAgICAgICAxNjgsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTEyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTM3LFxuICAgICAgICAyNTIsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzOSxcbiAgICAgICAgNzYsXG4gICAgICAgIDE2NixcbiAgICAgICAgOTIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTk0LFxuICAgICAgICA1NyxcbiAgICAgICAgMTQ0LFxuICAgICAgICA3MyxcbiAgICAgICAgMjQsXG4gICAgICAgIDU5LFxuICAgICAgICAzNixcbiAgICAgICAgMTEsXG4gICAgICAgIDQwLFxuICAgICAgICAzNCxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNSxcbiAgICAgICAgMjAsXG4gICAgICAgIDEwLFxuICAgICAgICA1NixcbiAgICAgICAgMzIsXG4gICAgICAgIDEyLFxuICAgICAgICAxOTcsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTAsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjMzLFxuICAgICAgICAyMzEsXG4gICAgICAgIDExMixcbiAgICAgICAgNjksXG4gICAgICAgIDkwLFxuICAgICAgICAxMjFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE2NCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgNzZcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjE0LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA2NixcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICA2NVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk3LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjAxLFxuICAgICAgICAyNyxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMyxcbiAgICAgICAgMjM3LFxuICAgICAgICA5NyxcbiAgICAgICAgNjksXG4gICAgICAgIDE3NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDI0LFxuICAgICAgICAxODcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTcxLFxuICAgICAgICAyMDQsXG4gICAgICAgIDI0NixcbiAgICAgICAgODEsXG4gICAgICAgIDk4LFxuICAgICAgICAzMyxcbiAgICAgICAgMTg4LFxuICAgICAgICA3OCxcbiAgICAgICAgMjE1LFxuICAgICAgICAyMjQsXG4gICAgICAgIDM3LFxuICAgICAgICAxNjIsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTEyLFxuICAgICAgICA4OCxcbiAgICAgICAgMTMxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDI5LFxuICAgICAgICA4MixcbiAgICAgICAgMjQzLFxuICAgICAgICAxNTUsXG4gICAgICAgIDQwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjUyLFxuICAgICAgICAxMjYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTEzLFxuICAgICAgICA3LFxuICAgICAgICAxMTQsXG4gICAgICAgIDU2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTY0LFxuICAgICAgICAyNTEsXG4gICAgICAgIDEwMyxcbiAgICAgICAgODQsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTUxLFxuICAgICAgICA3NSxcbiAgICAgICAgMTA0LFxuICAgICAgICA3NixcbiAgICAgICAgNjksXG4gICAgICAgIDIwNixcbiAgICAgICAgMjEwLFxuICAgICAgICA0XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNTUsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiWTBIUDBYMVVmREJtalZjcjJtY2NZUTNzSkhyV1RHUENSR3NYWFdMRWZ2VT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiRHdBVW9yYk9SbU9BOVJZcGNCcW9PQVwiLFxuICBcInBob25lSWRcIjogXCI1NTAyOTI4OS02YTM1LTQ2YjgtOGIzOC01ODZkYTNhMTI5ZjVcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjI3LFxuICAgICAgMTYwLFxuICAgICAgMjM5LFxuICAgICAgMTE2LFxuICAgICAgNDYsXG4gICAgICAxMDQsXG4gICAgICA3MSxcbiAgICAgIDEyNCxcbiAgICAgIDE5MCxcbiAgICAgIDIwOCxcbiAgICAgIDIyMyxcbiAgICAgIDU4LFxuICAgICAgMTQsXG4gICAgICAyMzIsXG4gICAgICA3MSxcbiAgICAgIDExOSxcbiAgICAgIDUzLFxuICAgICAgOTYsXG4gICAgICAxMjgsXG4gICAgICAxNDJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTgyLFxuICAgICAgMzUsXG4gICAgICA3OCxcbiAgICAgIDIxMixcbiAgICAgIDI0NCxcbiAgICAgIDEzMSxcbiAgICAgIDEzMixcbiAgICAgIDE5MSxcbiAgICAgIDU2LFxuICAgICAgMTg4LFxuICAgICAgMjMwLFxuICAgICAgMTQ1LFxuICAgICAgMjU1LFxuICAgICAgMzYsXG4gICAgICAyMzcsXG4gICAgICAzLFxuICAgICAgMjA4LFxuICAgICAgMTIyLFxuICAgICAgMjM3LFxuICAgICAgMjVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiMVFHUVlSUUdcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzQ3ODM1MTg5OTo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxNDYxNDEwNjA1NzUyNjU6NEBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNLM2ZyNjBHRUlyMHpyZ0dHQU1nQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjVraHZ6aUF3RUhpWHZ0M1VzVVJwSUM1ZWdlbTlUajk5NWt6cWZiTG4wanM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiUFNmMmt2MGZiNjVQQlc1T2V1V3l3dnBVTlJRMlNkbDJ1U1c3U0VvSnhCUjJGUUk1NzB0Q3pLeDJ2bXRVa0MxdzMvVXhDR0xacS81UFdMT2JaSGtqQlE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiOGRhK0ZBSHJVWnpjenVEaU5RekFBRHV1UU5BdW5IVU53SW1OTUh0aVNHK052ZkFIZllvUGhJZWJqWEFEY2p1eWJNbFAxTWZIQW0rRmJzUHQ5N09DQnc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzNDc4MzUxODk5OjRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAzMixcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDU5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjkzNDYwNjIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFNOTVcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU05NS5qc29uIjogIntcImtleURhdGFcIjpcImN2cnZYOFlIYVIzOXhlYWlFbjdxWEV4K2RoeVM2ekpLNnQrTThmUkRUR2c9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTcwNTc2NjgyOSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI5MzQ1OTgzOTQzXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
